services:
  - type: web
    name: nexusai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    healthCheckPath: /health
    healthCheckInterval: 600  # 10 minutos em segundos
    autoDeploy: true